# Generated by Django 3.2.3 on 2021-08-20 20:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videobaslik', models.CharField(max_length=100, null=True, unique=True, verbose_name='Video Başlık')),
                ('videoid', models.CharField(max_length=100, null=True, unique=True, verbose_name='Video İd')),
                ('videoaciklama', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('videourl', models.URLField(max_length=20, null=True)),
                ('erisim', models.BooleanField(default=True)),
                ('tarih', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
