# Generated by Django 3.2.3 on 2021-08-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoders',
            name='videoid',
        ),
        migrations.AlterField(
            model_name='videoders',
            name='videourl',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
