# Generated by Django 3.2.3 on 2021-08-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoders', '0002_auto_20210820_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoders',
            name='videoid',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Video İd'),
        ),
    ]
