# Generated by Django 3.2.3 on 2021-06-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makale',
            old_name='ad',
            new_name='isim',
        ),
        migrations.AlterField(
            model_name='makale',
            name='resim',
            field=models.ImageField(default='makale.jpg', upload_to='makale/%Y/%m/%d/'),
        ),
    ]