# Generated by Django 3.2.3 on 2021-08-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0003_auto_20210809_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='makale',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='makale.kategori'),
        ),
    ]
