# Generated by Django 3.2.3 on 2021-08-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0006_etiket'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='etiketler',
            field=models.ManyToManyField(blank=True, null=True, to='makale.Etiket'),
        ),
    ]
