# Generated by Django 3.2.3 on 2021-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0007_makale_etiketler'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
