# Generated by Django 3.2.3 on 2021-09-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0009_rename_slug_makale_makale_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='meta_tags',
            field=models.JSONField(blank=True, default=dict, verbose_name='meta tags'),
        ),
    ]
