# Generated by Django 3.2.3 on 2021-09-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0010_kategori_meta_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='meta_tags',
        ),
    ]
