# Generated by Django 3.2.3 on 2021-09-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0012_auto_20210906_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='etiketler',
            field=models.TextField(blank=True, null=True),
        ),
    ]
