# Generated by Django 3.2.3 on 2021-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrin',
            name='yazar',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Alternatif metin'),
        ),
    ]
