# Generated by Django 3.2.3 on 2021-06-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Video dersin başlığı..', max_length=200, unique=True, verbose_name='Ders Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('resim', models.ImageField(default='videolar/varsayilan.jpg', upload_to='videolar/%Y/%m/%d/')),
                ('tarih', models.DateTimeField(auto_now=True)),
                ('erisim', models.BooleanField(default=True)),
            ],
        ),
    ]
