# Generated by Django 3.2.3 on 2021-06-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoders',
            old_name='ad',
            new_name='isim',
        ),
        migrations.AlterField(
            model_name='videoders',
            name='resim',
            field=models.ImageField(default='varsayilan.jpg', upload_to='videolar/%Y/%m/%d/'),
        ),
    ]
