# Generated by Django 3.2.3 on 2021-09-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='i̇letisim',
            old_name='adsoyad',
            new_name='ad_soyad',
        ),
    ]
