# Generated by Django 3.2.3 on 2021-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0002_rename_adsoyad_i̇letisim_ad_soyad'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇letisim',
            name='okundu',
            field=models.BooleanField(default=False),
        ),
    ]
