# Generated by Django 3.2.3 on 2021-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0004_ayarlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='footer_aciklama',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_aciklama_baslik',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='Footer açıklama başlık'),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_facebook',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_iletisim_aciklama',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_iletisim_baslik',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='İletişim başlık'),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_iletisim_konum',
            field=models.CharField(blank=True, max_length=50, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_iletisim_mail',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mail'),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_iletisim_tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon numarası'),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_instagram',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_mail_baslik',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mail başlık'),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_mail_mail',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mail'),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_twitter',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='footer_youtube',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='anasayfa_2seviye_baslik',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Anasayfa 2. Seviye Başlık'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='anasayfa_4seviye_baslik',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Anasayfa 4. Seviye Başlık'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='anasayfa_5seviye_baslik',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Anasayfa 5. Seviye Başlık'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='anasayfa_6seviye_baslik',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Anasayfa 6. Seviye Başlık'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='anasayfa_banner_baslik',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Anasayfa Başlık'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='anasayfa_video_baslik',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Anasayfa Videolar Başlık'),
        ),
    ]
