# Generated by Django 3.2.3 on 2021-09-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0005_auto_20210904_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayarlar',
            name='footer_mail_mail',
        ),
    ]
