# Generated by Django 3.2.3 on 2021-09-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0006_remove_ayarlar_footer_mail_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayarlar',
            name='footer_iletisim_mail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='footer_mail_baslik',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mail başlık'),
        ),
    ]
