# Generated by Django 3.2.3 on 2021-09-05 12:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0007_auto_20210904_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayarlar',
            name='color',
            field=colorfield.fields.ColorField(default='#0e3746', max_length=18),
        ),
    ]
