# Generated by Django 3.2.3 on 2021-09-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0008_alter_ayarlar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='anasayfa_video_resim',
            field=models.ImageField(default='varsayilan.jpg', upload_to='makale/%Y/%m/%d/'),
        ),
    ]
