# Generated by Django 3.2.3 on 2021-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0009_ayarlar_anasayfa_video_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='anasayfa_logo',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Logo İsim'),
        ),
    ]
