# Generated by Django 3.2.3 on 2021-09-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0011_auto_20210906_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayarlar',
            name='meta_anasayfa_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
