# Generated by Django 3.2.3 on 2021-09-17 12:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0013_auto_20210906_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='anasayfa_banner_aciklama2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='anasayfa_banner_baslik2',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Anasayfa Başlık'),
        ),
    ]
