# Generated by Django 3.2.3 on 2021-09-19 02:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0014_auto_20210917_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayarlar',
            name='footer_iletisim_aciklama',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
