# Generated by Django 3.2.3 on 2021-08-24 14:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim_isim', models.CharField(max_length=100, null=True, unique=True, verbose_name='Video Başlık')),
                ('resim_aciklama', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('resim', models.ImageField(default='varsayilan.jpg', upload_to='makale/%Y/%m/%d/')),
                ('erisim', models.BooleanField(default=True)),
                ('tarih', models.DateTimeField(auto_now=True)),
                ('resim_alt', models.CharField(max_length=100, null=True, unique=True, verbose_name='Alternatif metin')),
            ],
        ),
    ]
