# Generated by Django 3.2.3 on 2021-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='resim_isim',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Resim Başlık'),
        ),
    ]
